# Generated by Django 3.1.2 on 2020-11-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intern', '0002_auto_20201108_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Body',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
